# Generated by Django 4.2.13 on 2024-06-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_source', models.CharField(max_length=255, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expected_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haircut_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=10)),
                ('revenue_source', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('expected_duration', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('invoice_number', 'customer')},
            },
        ),
    ]
